#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server
# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/

# Check the exit status of the scp command
#if [ $? -eq 0 ]; then
#    echo "File transferred successfully."
#else
#    echo "Error: File transfer failed."
#fi
