#!/usr/bin/env bash
# A bash script to install and set up Nginx
# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a default index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Ensure Nginx is listening on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart
