#!/usr/bin/env bash
#Install nginx on your server
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
new_page="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "47s|.*|$new_page|" /etc/nginx/sites-available/default
sudo service nginx restart
