#!/usr/bin/env bash
#Install load balancer HAproxy

sudo apt-get -y update
sudo apt install -y haproxy
echo "
frontend http
	bind *:80
	mode http
	default_backend web
	
	
backend web
	balance roundrobin
	server web-01 100.26.218.239:80 check
	server web-02 54.158.205:80 check" >> /etc/haproxy/haproxy.cfg

sudo systemctl enable haproxy
sudo systemctl restart haproxy
