#!/usr/bin/env bash
#Install load balancer HAproxy

sudo apt-get -y update
sudo apt install -y haproxy
echo "
frontend http
	bind *:80
	mode http
	default_backend web
	
	
backend web
	balance roundrobin
	server web-01 34.229.68.181:80 check
	server web-02 34.232.66.229:80 check" >> /etc/haproxy/haproxy.cfg

sudo systemctl enable haproxy
sudo systemctl restart haproxy
