#!/usr/bin/env bash
# Printing "Best School" with a while loop and printing "HI" on 9th iteration
a=0
while [ "$a" -lt 10 ]; do
	if [ "$a" -eq 8 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
    ((a++))

done