#!/usr/bin/env bash
# Check if Gunicorn is running

if pgrep -x "gunicorn" > /dev/null
then
    #echo "Reloading Gunicorn gracefully..."
    
    # Find the process ID of Gunicorn
    gunicorn_pid=$(pgrep -x "gunicorn")
    
    # Send a HUP signal to the Gunicorn master process
    kill -HUP "$gunicorn_pid"
 
fi
